---
  - hosts: all
    tasks:

    - name: Set root to login to MySQL using the unix_socket
      mysql_user:
        name: root
        plugin: unix_socket
        password: ''
        login_unix_socket: /run/mysqld/mysqld.sock
        priv: '*.*:ALL,GRANT'

    - name: Remove anonymous user from mysql
      mysql_user:
        name: ''
        host_all: yes
        login_unix_socket: /run/mysqld/mysqld.sock
        state: absent

    - name: Remove the test database from mysql
      mysql_db:
        db: test
        login_unix_socket: /run/mysqld/mysqld.sock
        state: absent

    - name: Restart service mariadb
      service:
        name: mariadb
        state: restarted
